### ISSUE TITLE
Two parts hl10NoseCone and hl10TailCone use a deprecated module

### ISSUE THREAD

**Issue by enceos** [Angel-125/Airships#2]
I found that two parts, hl10NoseCone and hl10TailCone, use your deprecated module WBIModelToggle:

    MODULE
    {
        name = WBIModelToggle
        meshTransforms = EndCap
    }

Plus hl10HangarDeck uses a module WBIGasStation, which is also not present in the current version of WildBlueTools

**Comment by Angel-125** [comment]
Thanks, it'll get fixed in the next release. :)
