### ISSUE TITLE
parts missing

### ISSUE THREAD

**Issue by lolelbug** [Angel-125/Airships#5]
i am trying it out in 1.4 btw

some parts are missing (dirigible parts) for example: Dirigible "middle" parts , cargo parts etc

**Comment by lolelbug** [comment]
Update: the flight deck parts are almost gone from my game

            i dont have a HL-10 PARTS unless the nose/tail cone

**Comment by Angel-125** [comment]
Heisenberg isn't updated to 1.4.1 yet.
