### ISSUE TITLE
attachment nodes in BisonHub.cfg

### ISSUE THREAD

**Issue by Yitscar** [Angel-125/Airships#6]
In BisonHub.cfg there are 2 nodes called back and 2 nodes called front
This screwed up my game when I played around with KIS. Shoudn't 2 of them be called left and right ?

	node_stack_top = 0, 0, -0.982, 0, 0, -1, 2
	node_stack_bottom = 0, 0, 0.923, 0, 0, 1, 2
	node_stack_front = 0, 1.3, 0, 0, 1, 0, 2
	node_stack_back = 0, -1.3, 0, 0, -1, 0, 2
	node_stack_front = 1.3, 0, 0, 1, 0, 0, 2
	node_stack_back = -1.3, 0, 0, -1, 0, 0, 2

**Comment by Angel-125** [comment]
Updated for next commit. Thanks! :)
